version: '3'

services:

  ## Zookeeper

  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888

  ## Kafka
  kafka1:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:19091"
    depends_on:
      - kafka1

  ### Flink
  #  jobmanager:
  #    image: flink:latest
  #    container_name: jobmanager
  #    ports:
  #      - "8081:8081"
  #    command: jobmanager
  #    volumes:
  #      - "../target:/target"
  #    environment:
  #      - |
  #        FLINK_PROPERTIES=
  #        jobmanager.rpc.address: jobmanager
  #
  #  taskmanager:
  #      image: flink:latest
  #      container_name: taskmanager
  #      depends_on:
  #        - jobmanager
  #      command: taskmanager
  #      environment:
  #        - |
  #          FLINK_PROPERTIES=
  #          jobmanager.rpc.address: jobmanager
  #          taskmanager.numberOfTaskSlots: 4

