version: '3'

services:

  ## Zookeeper

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  ## Kafka
  kafka1:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka1
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

    # Broker 2 di Kafka
  kafka2:
      image: docker.io/bitnami/kafka:latest
      container_name: kafka2
      ports:
        - "9094:9093"
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:9092,EXTERNAL://localhost:9094
        - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      depends_on:
        - zookeeper

  kafka3:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka3
    ports:
      - "9095:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:9092,EXTERNAL://localhost:9095
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  ### Flink
  #  jobmanager:
  #    image: flink:latest
  #    container_name: jobmanager
  #    ports:
  #      - "8081:8081"
  #    command: jobmanager
  #    volumes:
  #      - "../target:/target"
  #    environment:
  #      - |
  #        FLINK_PROPERTIES=
  #        jobmanager.rpc.address: jobmanager
  #
  #  taskmanager:
  #      image: flink:latest
  #      container_name: taskmanager
  #      depends_on:
  #        - jobmanager
  #      command: taskmanager
  #      environment:
  #        - |
  #          FLINK_PROPERTIES=
  #          jobmanager.rpc.address: jobmanager
  #          taskmanager.numberOfTaskSlots: 4

