version: '3'

services:

  ## Zookeeper

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  ## Kafka
  kafka:
      image: 'bitnami/kafka:latest'
      container_name: kafka
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
        - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
        - KAFKA_BROKER_ID= 2
      ports:
        - '9092:9092'
        - '9093:9093'
      depends_on:
        - zookeeper

  ### Flink
  #  jobmanager:
  #    image: flink:latest
  #    container_name: jobmanager
  #    ports:
  #      - "8081:8081"
  #    command: jobmanager
  #    volumes:
  #      - "../target:/target"
  #    environment:
  #      - |
  #        FLINK_PROPERTIES=
  #        jobmanager.rpc.address: jobmanager
  #
  #  taskmanager:
  #      image: flink:latest
  #      container_name: taskmanager
  #      depends_on:
  #        - jobmanager
  #      command: taskmanager
  #      environment:
  #        - |
  #          FLINK_PROPERTIES=
  #          jobmanager.rpc.address: jobmanager
  #          taskmanager.numberOfTaskSlots: 4

